cmake_minimum_required(VERSION 3.22.1)
project(u1field LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include(FetchContent)
set(WHISPER_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_SERVER OFF CACHE BOOL "" FORCE)
set(GGML_OPENMP OFF CACHE BOOL "" FORCE)
FetchContent_Declare(whispercpp GIT_REPOSITORY https://github.com/ggml-org/whisper.cpp.git GIT_TAG 1da4dc82fa7996d4edda05890dca65aeceaafd6d)
FetchContent_MakeAvailable(whispercpp)
add_library(u1whisper SHARED u1_whisper_jni.cpp)
target_link_libraries(u1whisper PRIVATE whisper log android)
target_compile_options(u1whisper PRIVATE -O3 -fvisibility=hidden)
